ボウリング計算プログラムを作成
tatuya4451/ruby-practices pull request #4
Opened 2021-02-10 13:51 UTC by tatuya4451

# 実装の目的/背景
[ボウリングのスコア計算プログラム \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/practices/210)
フィヨルドブートキャンプのプラクティスでボウリングスコア計算プログラムを作成

2021-02-14 14:52 UTC, kakutani requested changes
コードの見た目で気になったところをコメントしました。

2021-02-14 14:52 UTC, kakutani commented on 04.bowling/bowling.rb
> +  shots << if s == 'X'
インデントがとても深くなってしまうので、これぐらいの簡単な`if`文であれば、三項演算子を使うと良いです(1行で書けます)

2021-02-14 14:52 UTC, kakutani commented on 04.bowling/bowling.rb
> +    break
この`break`は無くても良さそうに見えます(細かく追えてませんが、無いとおかしくなるのかな…)

2021-02-14 14:52 UTC, kakutani commented on 04.bowling/bowling.rb
> +    break
この`break`も不要そうな気がします…(見落しがあったらすみません)

2021-02-14 14:52 UTC, kakutani commented on 04.bowling/bowling.rb
> +
この空行は不要だと思います(次行の`elsif`が区切りになっているので、この空行には意味が無さそう)

2021-02-14 14:52 UTC, kakutani commented on 04.bowling/bowling.rb
> +
この空行は不要だと思います(次行の`elsif`が区切りになっているので、この空行には意味が無さそう)

2021-02-14 14:52 UTC, kakutani commented on 04.bowling/bowling.rb
> +  end
`else`が無いのが気になりました。文法上は無くても大丈夫なのですが、条件分岐が複雑なのでこれら以外のケースがあったらどうなるのかな?と気になりました。

2021-02-14 14:56 UTC, kakutani commented
`if - elsif`の分岐の条件が複雑だなあ、と思いながら読んでいました。
コードを良くみると、
* まず`frame_count == 10`(最終フレーム)のときと、それ以外(`else`)のときという場合分けがありそうです
* それぞれのフレーム(10フレーム目と、1〜9フレーム目)で、点数の計算の方法を整理してみるとよさそうですね。

2021-02-15 00:04 UTC, tatuya4451 commented on 04.bowling/bowling.rb
> +  shots << if s == 'X'
修正します！

2021-02-15 00:07 UTC, tatuya4451 commented on 04.bowling/bowling.rb
> +    break
このbreakが無かったらここで式が終わらず余分な計算をしてしまいスコアがおかしくなるので必要かと思います:sweat:

2021-02-15 00:08 UTC, tatuya4451 commented on 04.bowling/bowling.rb
> +    break
このbreakが無かったらここで式が終わらず余分な計算をしてしまいスコアがおかしくなるので必要かと思います:sweat:

2021-02-15 00:08 UTC, tatuya4451 commented on 04.bowling/bowling.rb
> +
修正します！

2021-02-15 00:08 UTC, tatuya4451 commented on 04.bowling/bowling.rb
> +
修正します！

2021-02-15 00:16 UTC, tatuya4451 commented on 04.bowling/bowling.rb
> +  end
これら以外のケースは shots_count += 1 frame_score += sこの2行が実行されるだけの処理になっております。

2021-02-15 03:13 UTC, kakutani commented on 04.bowling/bowling.rb
> +scores.each do |s|
`each`の中で`shots`に追加していますが、Rubyには `Enumerable#map`という便利なメソッドもあるので、せっかくだから使ってみましょうか。

2021-02-15 03:15 UTC, kakutani commented on 04.bowling/bowling.rb
> +    break
私の勘違いでした。`shots`に対する繰り返しだから必要なのですね。

2021-02-15 03:15 UTC, kakutani commented on 04.bowling/bowling.rb
> +    break
ここも私の勘違いでした。`shots`に対する繰り返しだから必要なのですね。

2021-02-15 03:22 UTC, kakutani commented on 04.bowling/bowling.rb
> +  end
流派によるのですが、意図的に省いているのか書き忘れなのかがわからないので、

```ruby
..
else
  # do nothing
end
```
と書くやり方もあります。ご参考まで。

2021-02-15 04:39 UTC, tatuya4451 commented on 04.bowling/bowling.rb
> +  end
そういった書き方もあるのですね！今回はその書き方をしたらrubocopに引っかかったのでelseは無しで行こうと思います。

2021-02-15 04:52 UTC, tatuya4451 commented on 04.bowling/bowling.rb
> +scores.each do |s|
修正します！

2021-02-15 06:25 UTC, kakutani commented on 04.bowling/bowling.rb
> +scores = score.chars
ここは7行目にまとめてしまってよさそう。

2021-02-15 06:25 UTC, kakutani commented on 04.bowling/bowling.rb
> +  end
あー、rubocop。なるほど。

2021-02-15 06:28 UTC, kakutani commented on 04.bowling/bowling.rb
> +shots.each_with_index do |s, i|
ブロックの中身が数行であれば、ブロックパラメータの名前は短くてもよいと思います。
が、こではけっこう長いので、`shot` と明示したほうがよさそうです。
`s`だけ妙に短かくてバランスが悪い。

`i`は、`shots`のインデックスなので、これは `i` でよさそうです。

2021-02-15 10:40 UTC, tatuya4451 commented on 04.bowling/bowling.rb
> +shots.each_with_index do |s, i|
了解しました！修正します！

2021-02-15 10:46 UTC, tatuya4451 commented on 04.bowling/bowling.rb
> +scores = score.chars
了解しました！修正します！

2021-02-15 11:27 UTC, merged